export const data = [
    {
        id: "4aF0F8w7yXX9o5_QFky_ig",
        alias: "celestine-brooklyn",
        name: "Celestine",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/J5HuHor_cmVEG6HhQtFeDw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/celestine-brooklyn?adjust_creative=lXwNMOnoO3qbv5EBsmc8vA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=lXwNMOnoO3qbv5EBsmc8vA",
        review_count: 227,
        categories: [[Object], [Object]],
        rating: 4,
        coordinates: { latitude: 40.704676, longitude: -73.987975 },
        transactions: ["delivery"],
        price: "$$$",
        location: {
            address1: "1 John St",
            address2: "",
            address3: null,
            city: "Brooklyn",
            zip_code: "11201",
            country: "US",
            state: "NY",
            display_address: [Array],
        },
        phone: "+17185225356",
        display_phone: "(718) 522-5356",
        distance: 539.4069533813018,
    },
    {
        id: "4aF0F8w7yXX9o5_QFky_ig",
        alias: "Restaurant2-brooklyn",
        name: "Restaurant2",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/J5HuHor_cmVEG6HhQtFeDw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/celestine-brooklyn?adjust_creative=lXwNMOnoO3qbv5EBsmc8vA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=lXwNMOnoO3qbv5EBsmc8vA",
        review_count: 227,
        categories: [[Object], [Object]],
        rating: 5,
        coordinates: { latitude: 40.604676, longitude: -73.887975 },
        transactions: ["delivery"],
        price: "$$$$",
        location: {
            address1: "1 John St",
            address2: "",
            address3: null,
            city: "Brooklyn",
            zip_code: "11201",
            country: "US",
            state: "NY",
            display_address: [Array],
        },
        phone: "+17185225356",
        display_phone: "(718) 522-5356",
        distance: 519.4069533813018,
    },
    {
        id: "4aF0F8w7yXX9o5_QFky_ig",
        alias: "Restaurant3-brooklyn",
        name: "Restaurant3",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/J5HuHor_cmVEG6HhQtFeDw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/celestine-brooklyn?adjust_creative=lXwNMOnoO3qbv5EBsmc8vA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=lXwNMOnoO3qbv5EBsmc8vA",
        review_count: 227,
        categories: [[Object], [Object]],
        rating: 3,
        coordinates: { latitude: 40.404676, longitude: -74.187975 },
        transactions: ["delivery"],
        price: "$",
        location: {
            address1: "1 John St",
            address2: "",
            address3: null,
            city: "Brooklyn",
            zip_code: "11201",
            country: "US",
            state: "NY",
            display_address: [Array],
        },
        phone: "+17185225356",
        display_phone: "(718) 522-5356",
        distance: 539.4069533813018,
    },
]
